stages:
  - build
  - package

build:
  stage: build
  image: java:8
  before_script:
    # Enable the usage of sources over https
    - apt-get update -yqq
    - apt-get install apt-transport-https -yqq
    # Add keyserver for SBT
    - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
    # Install SBT
    - apt-get update -yqq
    - apt-get install sbt -yqq
    # Log the sbt version
    - sbt sbt-version
  script:
    - sbt compile dist --supershell=false
  artifacts:
    paths:
      - target/universal/

docker-build:
  stage: package
  image: docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -f Dockerfile --build-arg configfile=$CONF_DEVELOP -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
