stages:
#  - build
#  - package
  - migrate
#
#build:
#  stage: build
#  image: hseeberger/scala-sbt:8u222_1.3.4_2.13.1
#  variables:
#    SBT_OPTS: "-Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy"
##  cache:
##    key: "$CI_BUILD_REF_NAME" # contains either the branch or the tag, so it's caching per branch
##    untracked: true
##    paths:
##      - "sbt-cache/.ivy/cache"
##      - "sbt-cache/.boot"
##      - "sbt-cache/.sbtboot"
#  script:
#    - sbt clean compile dist --supershell=false
#  artifacts:
#    paths:
#      - target/universal/
#
#docker-build:
#  stage: package
#  image: docker:stable
#  services:
#    - docker:dind
#  variables:
#    DOCKER_DRIVER: overlay
#  script:
#    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
#    - docker build -t "$CI_REGISTRY_IMAGE:latest" .
#    - docker push "$CI_REGISTRY_IMAGE:latest"

database-migrate:
  stage: migrate
  image: docker:stable
  services:
    - docker:dind
  variables:
    FLYWAY_EDITION: community
  script:
    - docker pull flyway/flyway
    - docker run --rm -v ${PWD}/sql:/flyway/sql flyway/flyway -url=jdbc:h2:mem:test -user=sa migrate
