name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build jar
      run: sbt compile dist
    
    - name: Cache Coursier dependencies
      uses: actions/cache@v1
      with:
       path: ~/.cache/coursier
       key: ${{ runner.os }}-${{ github.ref }}-coursier
       restore-keys: |
        ${{ runner.os }}-${{ github.ref }}-coursier
        
    - name: Cache Ivy dependencies
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-${{ github.ref }}-ivy2
        restore-keys: |
         ${{ runner.os }}-${{ github.ref }}-ivy2

    - name: Build docker image
      run:
        docker build -t hellome .
        
    - name: Push docker image
      run: |
        docker login docker.pkg.github.com -u belizwp -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
        docker tag hellome docker.pkg.github.com/belizwp/hellome/app:latest
        docker push docker.pkg.github.com/belizwp/hellome/app:latest
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}

  migrate:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Miigrate using flyway
        run:
          docker run --rm -v ${PWD}/sql:/flyway/sql flyway/flyway -url=jdbc:h2:mem:test -user=sa migrate
